"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Globe, Lock, RefreshCw, Search, FolderOpen } from "lucide-react";

export default function AdminAssessmentsPage() {
  const router = useRouter();
  const [token, setToken] = useState<string | null>(null);
  const [assessments, setAssessments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    const t = localStorage.getItem("adminToken");
    if (!t) { router.push("/admin/login"); return; }
    setToken(t);
  }, []);

  useEffect(() => {
    if (!token) return;
    fetchAssessments();
  }, [token]);

  const fetchAssessments = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/admin/assessments", {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (res.ok) setAssessments(data.assessments || []);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  const filtered = assessments.filter((a) =>
    a.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    a.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
    (a.createdByTeacherName || "").toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="p-8 space-y-8 animate-in fade-in slide-in-from-bottom duration-300 text-gray-900">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-black tracking-tight text-gray-900">All Platform Assessments</h2>
          <p className="text-sm text-gray-600 mt-1">
            Monitor every assessment generated by all activated teachers across the institution.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" />
            <input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search title, subject or teacher..."
              className="bg-white border border-gray-300 rounded-none pl-9 pr-4 py-2.5 text-xs focus:border-[#20407D] focus:ring-1 focus:ring-[#20407D] outline-none w-72 text-gray-900"
            />
          </div>
          <button 
            onClick={fetchAssessments} 
            className="p-2.5 bg-white border border-gray-300 rounded-none text-gray-600 hover:text-gray-900 transition-colors shadow-sm cursor-pointer"
          >
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
          </button>
        </div>
      </div>

      {/* Stats bar */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Total Assessments</p>
          <p className="text-3xl font-black mt-2 text-gray-900">{loading ? "—" : assessments.length}</p>
        </div>
        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Public Scope</p>
          <p className="text-3xl font-black mt-2 text-[#20407D]">{loading ? "—" : assessments.filter(a => a.isPublic).length}</p>
        </div>
        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Private Scope</p>
          <p className="text-3xl font-black mt-2 text-gray-600">{loading ? "—" : assessments.filter(a => !a.isPublic).length}</p>
        </div>
      </div>

      {/* Table Card */}
      <div className="bg-white/80 border border-gray-300 rounded-none overflow-hidden shadow-sm backdrop-blur-sm">
        {loading ? (
          <div className="h-64 flex items-center justify-center">
            <RefreshCw size={28} className="animate-spin text-[#20407D]" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="h-64 flex flex-col items-center justify-center gap-2 text-gray-500">
            <FolderOpen size={36} className="text-gray-400" />
            <p className="font-bold">{searchQuery ? "No results match your search" : "No assessments generated yet"}</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="bg-gray-100 border-b border-gray-300 text-gray-700 font-bold uppercase tracking-wider">
                  <th className="px-6 py-4">Assessment Title</th>
                  <th className="px-6 py-4">Subject</th>
                  <th className="px-6 py-4">Chapter</th>
                  <th className="px-6 py-4">Questions</th>
                  <th className="px-6 py-4">Duration</th>
                  <th className="px-6 py-4">Created By</th>
                  <th className="px-6 py-4">Scope</th>
                  <th className="px-6 py-4">Date</th>
                  <th className="px-6 py-4">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filtered.map((a) => {
                  const qs = Array.isArray(a.questions) ? a.questions : JSON.parse(a.questions || "[]");
                  return (
                    <tr key={a.id} className="hover:bg-gray-50/50 transition-colors text-gray-800">
                      <td className="px-6 py-4">
                        <span className="font-bold text-gray-900 block max-w-[200px] truncate">{a.title}</span>
                      </td>
                      <td className="px-6 py-4 font-semibold">{a.subject}</td>
                      <td className="px-6 py-4 text-gray-600">{a.lesson}</td>
                      <td className="px-6 py-4 text-gray-600 font-medium">{qs.length} Qs</td>
                      <td className="px-6 py-4 text-gray-600 font-mono font-medium">{a.duration}m</td>
                      <td className="px-6 py-4">
                        <span className="font-bold text-[#20407D] block">{a.createdByTeacherName || "System"}</span>
                        <span className="text-[9px] text-gray-500 block font-medium">{a.createdByEmail}</span>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-none text-[10px] font-bold border ${
                          a.isPublic 
                            ? "bg-[#20407D]/10 text-[#20407D] border-[#20407D]/20" 
                            : "bg-gray-100 text-gray-600 border-gray-300"
                        }`}>
                          {a.isPublic ? <Globe size={9} /> : <Lock size={9} />}
                          {a.isPublic ? "Public" : "Private"}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-gray-500 font-medium">{new Date(a.createdAt).toLocaleDateString()}</td>
                      <td className="px-6 py-4">
                        <Link
                          href={`/admin/assessments/${a.id}`}
                          className="bg-gray-100 hover:bg-[#20407D] hover:text-white px-3.5 py-1.5 rounded-none border border-gray-300 hover:border-[#20407D] transition-all text-[11px] font-bold text-gray-700"
                        >
                          Inspect
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

