"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Globe, Lock, RefreshCw, Search, BookOpen, Clock, FolderOpen } from "lucide-react";

export default function AdminAssessmentsPage() {
  const router = useRouter();
  const [token, setToken] = useState<string | null>(null);
  const [assessments, setAssessments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    const t = localStorage.getItem("adminToken");
    if (!t) { router.push("/admin/login"); return; }
    setToken(t);
  }, []);

  useEffect(() => {
    if (!token) return;
    fetchAssessments();
  }, [token]);

  const fetchAssessments = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/admin/assessments", {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (res.ok) setAssessments(data.assessments || []);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  const filtered = assessments.filter((a) =>
    a.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    a.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
    (a.createdByTeacherName || "").toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="p-8 space-y-8 animate-in fade-in slide-in-from-bottom duration-300">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-black">All Platform Assessments</h2>
          <p className="text-sm text-slate-400 mt-1">
            Monitor every assessment generated by all activated teachers across the institution.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
            <input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search title, subject or teacher..."
              className="bg-slate-900/60 border border-white/5 rounded-xl pl-9 pr-4 py-2.5 text-xs focus:border-indigo-500 outline-none w-72"
            />
          </div>
          <button onClick={fetchAssessments} className="p-2.5 bg-slate-900/60 border border-white/5 rounded-xl text-slate-400 hover:text-white transition-colors">
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
          </button>
        </div>
      </div>

      {/* Stats bar */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-slate-900/40 border border-white/5 rounded-2xl p-4">
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Total Assessments</p>
          <p className="text-2xl font-black mt-1">{loading ? "—" : assessments.length}</p>
        </div>
        <div className="bg-slate-900/40 border border-white/5 rounded-2xl p-4">
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Public</p>
          <p className="text-2xl font-black mt-1 text-indigo-400">{loading ? "—" : assessments.filter(a => a.isPublic).length}</p>
        </div>
        <div className="bg-slate-900/40 border border-white/5 rounded-2xl p-4">
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Private</p>
          <p className="text-2xl font-black mt-1 text-slate-400">{loading ? "—" : assessments.filter(a => !a.isPublic).length}</p>
        </div>
      </div>

      {/* Table */}
      <div className="bg-slate-900/40 border border-white/5 rounded-3xl overflow-hidden shadow-2xl">
        {loading ? (
          <div className="h-64 flex items-center justify-center">
            <RefreshCw size={28} className="animate-spin text-indigo-400" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="h-64 flex flex-col items-center justify-center gap-2 text-slate-500">
            <FolderOpen size={36} className="text-slate-700" />
            <p className="font-bold">{searchQuery ? "No results match your search" : "No assessments generated yet"}</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="bg-slate-900/80 border-b border-white/5 text-slate-400 font-bold uppercase tracking-wider">
                  <th className="px-6 py-4">Assessment Title</th>
                  <th className="px-6 py-4">Subject</th>
                  <th className="px-6 py-4">Chapter</th>
                  <th className="px-6 py-4">Questions</th>
                  <th className="px-6 py-4">Duration</th>
                  <th className="px-6 py-4">Created By</th>
                  <th className="px-6 py-4">Scope</th>
                  <th className="px-6 py-4">Date</th>
                  <th className="px-6 py-4">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {filtered.map((a) => {
                  const qs = Array.isArray(a.questions) ? a.questions : JSON.parse(a.questions || "[]");
                  return (
                    <tr key={a.id} className="hover:bg-white/[0.02] transition-colors">
                      <td className="px-6 py-4">
                        <span className="font-bold text-white block max-w-[200px] truncate">{a.title}</span>
                      </td>
                      <td className="px-6 py-4 text-slate-300">{a.subject}</td>
                      <td className="px-6 py-4 text-slate-400">{a.lesson}</td>
                      <td className="px-6 py-4 text-slate-400">{qs.length} Qs</td>
                      <td className="px-6 py-4 text-slate-400 font-mono">{a.duration}m</td>
                      <td className="px-6 py-4">
                        <span className="font-bold text-indigo-400 block">{a.createdByTeacherName || "System"}</span>
                        <span className="text-[9px] text-slate-500 block">{a.createdByEmail}</span>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                          a.isPublic ? "bg-indigo-500/10 text-indigo-400 border border-indigo-500/20" : "bg-slate-800 text-slate-400 border border-white/5"
                        }`}>
                          {a.isPublic ? <Globe size={9} /> : <Lock size={9} />}
                          {a.isPublic ? "Public" : "Private"}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-slate-500">{new Date(a.createdAt).toLocaleDateString()}</td>
                      <td className="px-6 py-4">
                        <Link
                          href={`/admin/assessments/${a.id}`}
                          className="bg-white/5 hover:bg-indigo-500/10 hover:text-indigo-400 px-3.5 py-1.5 rounded-lg border border-white/5 hover:border-indigo-500/20 transition-all text-[11px] font-bold text-slate-400"
                        >
                          Inspect
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
