"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  Activity, Compass, CheckCircle, Globe, Lock, FolderOpen,
  PlusCircle, ArrowRight
} from "lucide-react";

export default function TeacherDashboardPage() {
  const router = useRouter();
  const [token, setToken] = useState<string | null>(null);
  const [teacher, setTeacher] = useState<any>(null);
  const [myAssessments, setMyAssessments] = useState<any[]>([]);
  const [publicAssessments, setPublicAssessments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const savedToken = localStorage.getItem("teacherToken");
    const savedUser = localStorage.getItem("teacherUser");
    if (!savedToken || !savedUser) {
      router.push("/teacher/login");
      return;
    }
    setToken(savedToken);
    setTeacher(JSON.parse(savedUser));
  }, []);

  useEffect(() => {
    if (!token) return;
    fetch("/api/teacher/assessment", {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then((r) => r.json())
      .then((data) => {
        setMyAssessments(data.myAssessments || []);
        setPublicAssessments(data.publicAssessments || []);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [token]);

  return (
    <div className="p-8 space-y-8 animate-in fade-in slide-in-from-bottom duration-300">
      {/* Header banner */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-slate-900/40 border border-white/5 rounded-3xl p-8 relative overflow-hidden shadow-2xl">
        <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/5 rounded-full blur-2xl" />
        <div>
          <h2 className="text-3xl font-black">Welcome back, {teacher?.userName || "Educator"}!</h2>
          <p className="text-sm text-slate-400 mt-1.5">
            Launch AI exam papers, customize questions, and monitor curriculum standards.
          </p>
        </div>
        <Link
          href="/teacher/generate"
          className="bg-emerald-600 hover:bg-emerald-500 px-6 py-3.5 rounded-2xl font-bold transition-all text-xs flex items-center gap-2 shadow-lg shadow-emerald-600/20 shrink-0"
        >
          <PlusCircle size={16} /> AI Assessment Workspace
        </Link>
      </div>

      {/* Quick Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
        <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Assessments Saved</span>
            <Activity size={18} className="text-emerald-400" />
          </div>
          <p className="text-4xl font-black">{loading ? "—" : myAssessments.length}</p>
          <p className="text-[10px] text-slate-500 mt-1">Generated by your profile</p>
        </div>

        <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Public Pool</span>
            <Compass size={18} className="text-indigo-400" />
          </div>
          <p className="text-4xl font-black">{loading ? "—" : publicAssessments.length}</p>
          <p className="text-[10px] text-slate-500 mt-1">Available from other teachers</p>
        </div>

        <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Class Turnout</span>
            <span className="h-2 w-2 bg-emerald-400 rounded-full animate-ping" />
          </div>
          <p className="text-4xl font-black text-emerald-400">96.4%</p>
          <p className="text-[10px] text-slate-500 mt-1">Average participation</p>
        </div>

        <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Pass Rate</span>
            <CheckCircle size={18} className="text-indigo-400" />
          </div>
          <p className="text-4xl font-black text-indigo-400">88.5%</p>
          <p className="text-[10px] text-slate-500 mt-1">Target benchmark exceeded</p>
        </div>
      </div>

      {/* Split dashboard sections */}
      <div className="grid lg:grid-cols-3 gap-8">
        {/* Recent Assessments */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold">Your Saved Assessments</h3>
            <Link href="/teacher/assessments" className="text-xs font-bold text-emerald-400 hover:underline flex items-center gap-1">
              View All <ArrowRight size={12} />
            </Link>
          </div>

          <div className="bg-slate-900/40 border border-white/5 rounded-3xl overflow-hidden shadow-xl">
            {loading ? (
              <div className="p-12 text-center text-slate-500 text-sm">Loading...</div>
            ) : myAssessments.length === 0 ? (
              <div className="p-12 text-center text-slate-500 space-y-2">
                <FolderOpen size={36} className="mx-auto text-slate-700" />
                <p className="text-sm">No assessments saved yet.</p>
                <Link href="/teacher/generate" className="inline-block mt-2 text-xs font-bold text-emerald-400 hover:underline">
                  Generate your first one →
                </Link>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="bg-slate-900/60 border-b border-white/5 text-slate-400 font-bold uppercase tracking-wider">
                      <th className="px-6 py-4">Title</th>
                      <th className="px-6 py-4">Subject</th>
                      <th className="px-6 py-4">Scope</th>
                      <th className="px-6 py-4">Questions</th>
                      <th className="px-6 py-4">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {myAssessments.slice(0, 5).map((a) => {
                      const qs = Array.isArray(a.questions) ? a.questions : JSON.parse(a.questions || "[]");
                      return (
                        <tr key={a.id} className="hover:bg-white/[0.02] transition-colors">
                          <td className="px-6 py-4 font-bold text-white max-w-[180px] truncate">{a.title}</td>
                          <td className="px-6 py-4 text-slate-300">{a.subject} • {a.lesson}</td>
                          <td className="px-6 py-4">
                            <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                              a.isPublic ? "bg-indigo-500/10 text-indigo-400 border border-indigo-500/20" : "bg-slate-800 text-slate-400 border border-white/5"
                            }`}>
                              {a.isPublic ? <Globe size={10} /> : <Lock size={10} />}
                              {a.isPublic ? "Public" : "Private"}
                            </span>
                          </td>
                          <td className="px-6 py-4 text-slate-400 font-bold">{qs.length} Qs</td>
                          <td className="px-6 py-4">
                            <Link href={`/teacher/assessments/${a.id}`} className="text-xs font-bold text-emerald-400 hover:underline">
                              Open
                            </Link>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>

        {/* Target Metrics */}
        <div className="space-y-4">
          <h3 className="text-base font-bold">Standard Target Metrics</h3>
          <div className="bg-slate-900/40 border border-white/5 rounded-3xl p-6 space-y-6 shadow-xl">
            {[
              { label: "Participation Turnout", desc: "High student response rates across activated batches.", value: "96%", color: "stroke-emerald-500", offset: "5.4" },
              { label: "Educator Pass Metrics", desc: "Dynamic evaluation grading benchmark averages.", value: "88%", color: "stroke-indigo-500", offset: "18.0" },
            ].map((gauge) => (
              <div key={gauge.label} className="flex items-center gap-4">
                <div className="relative h-14 w-14 flex items-center justify-center shrink-0">
                  <svg className="w-full h-full transform -rotate-90">
                    <circle cx="28" cy="28" r="24" className="stroke-slate-800 fill-transparent" strokeWidth="4" />
                    <circle cx="28" cy="28" r="24" className={`${gauge.color} fill-transparent`} strokeWidth="4" strokeDasharray="150.7" strokeDashoffset={gauge.offset} />
                  </svg>
                  <span className="absolute text-xs font-bold">{gauge.value}</span>
                </div>
                <div>
                  <p className="text-xs font-bold text-slate-200">{gauge.label}</p>
                  <p className="text-[10px] text-slate-400 leading-relaxed mt-0.5">{gauge.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
