"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  Activity, Compass, CheckCircle, Globe, Lock, FolderOpen,
  PlusCircle, ArrowRight
} from "lucide-react";

export default function TeacherDashboardPage() {
  const router = useRouter();
  const [token, setToken] = useState<string | null>(null);
  const [teacher, setTeacher] = useState<any>(null);
  const [myAssessments, setMyAssessments] = useState<any[]>([]);
  const [publicAssessments, setPublicAssessments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const savedToken = localStorage.getItem("teacherToken");
    const savedUser = localStorage.getItem("teacherUser");
    if (!savedToken || !savedUser) {
      router.push("/teacher/login");
      return;
    }
    setToken(savedToken);
    setTeacher(JSON.parse(savedUser));
  }, []);

  useEffect(() => {
    if (!token) return;
    fetch("/api/teacher/assessment", {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then((r) => r.json())
      .then((data) => {
        setMyAssessments(data.myAssessments || []);
        setPublicAssessments(data.publicAssessments || []);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [token]);

  return (
    <div className="p-8 space-y-8 animate-in fade-in slide-in-from-bottom duration-300 text-gray-900">
      {/* Header banner */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-[#C72323] text-white rounded-none p-8 relative overflow-hidden shadow-sm">
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-2xl" />
        <div className="relative z-10">
          <h2 className="text-3xl font-black tracking-tight text-white">Welcome back, {teacher?.userName || "Educator"}!</h2>
          <p className="text-sm text-red-100 mt-1.5 font-medium">
            Launch AI exam papers, customize questions, and monitor curriculum standards.
          </p>
        </div>
        <Link
          href="/teacher/generate"
          className="bg-white hover:bg-gray-100 text-[#C72323] px-6 py-3.5 rounded-none font-bold transition-all text-xs flex items-center gap-2 shadow-sm shrink-0 cursor-pointer relative z-10"
        >
          <PlusCircle size={16} /> AI Assessment Workspace
        </Link>
      </div>

      {/* Quick Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Assessments Saved</span>
            <Activity size={18} className="text-[#C72323]" />
          </div>
          <p className="text-4xl font-black text-gray-950">{loading ? "—" : myAssessments.length}</p>
          <p className="text-[10px] text-gray-500 mt-2 font-semibold">Generated by your profile</p>
        </div>

        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Public Pool</span>
            <Compass size={18} className="text-[#20407D]" />
          </div>
          <p className="text-4xl font-black text-gray-950">{loading ? "—" : publicAssessments.length}</p>
          <p className="text-[10px] text-gray-500 mt-2 font-semibold">Available from other teachers</p>
        </div>

        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Class Turnout</span>
            <span className="h-2.5 w-2.5 bg-emerald-600 rounded-full" />
          </div>
          <p className="text-4xl font-black text-emerald-700">96.4%</p>
          <p className="text-[10px] text-gray-500 mt-2 font-semibold">Average participation</p>
        </div>

        <div className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Pass Rate</span>
            <CheckCircle size={18} className="text-[#20407D]" />
          </div>
          <p className="text-4xl font-black text-[#20407D]">88.5%</p>
          <p className="text-[10px] text-gray-500 mt-2 font-semibold">Target benchmark exceeded</p>
        </div>
      </div>

      {/* Split dashboard sections */}
      <div className="grid lg:grid-cols-3 gap-8">
        {/* Recent Assessments */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold text-gray-900">Your Saved Assessments</h3>
            <Link href="/teacher/assessments" className="text-xs font-bold text-[#20407D] hover:text-[#C72323] flex items-center gap-1">
              View All <ArrowRight size={12} />
            </Link>
          </div>

          <div className="bg-white/80 border border-gray-300 rounded-none overflow-hidden shadow-sm backdrop-blur-sm">
            {loading ? (
              <div className="p-12 text-center text-gray-500 text-sm font-semibold">Loading your assessments...</div>
            ) : myAssessments.length === 0 ? (
              <div className="p-12 text-center text-gray-500 space-y-2">
                <FolderOpen size={36} className="mx-auto text-gray-400" />
                <p className="text-sm font-bold">No assessments saved yet.</p>
                <Link href="/teacher/generate" className="inline-block mt-2 text-xs font-bold text-[#20407D] hover:underline">
                  Generate your first one →
                </Link>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="bg-gray-100 border-b border-gray-300 text-gray-700 font-bold uppercase tracking-wider">
                      <th className="px-6 py-4">Title</th>
                      <th className="px-6 py-4">Subject</th>
                      <th className="px-6 py-4">Scope</th>
                      <th className="px-6 py-4">Questions</th>
                      <th className="px-6 py-4">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {myAssessments.slice(0, 5).map((a) => {
                      const qs = Array.isArray(a.questions) ? a.questions : JSON.parse(a.questions || "[]");
                      return (
                        <tr key={a.id} className="hover:bg-gray-50/50 transition-colors text-gray-800 font-medium">
                          <td className="px-6 py-4 font-bold text-gray-900 max-w-[180px] truncate">{a.title}</td>
                          <td className="px-6 py-4 text-gray-800">{a.subject} • {a.lesson}</td>
                          <td className="px-6 py-4">
                            <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-none text-[10px] font-bold border ${
                              a.isPublic 
                                ? "bg-[#20407D]/10 text-[#20407D] border-[#20407D]/20" 
                                : "bg-gray-100 text-gray-600 border-gray-300"
                            }`}>
                              {a.isPublic ? <Globe size={10} /> : <Lock size={10} />}
                              {a.isPublic ? "Public" : "Private"}
                            </span>
                          </td>
                          <td className="px-6 py-4 text-gray-650 font-bold">{qs.length} Qs</td>
                          <td className="px-6 py-4">
                            <Link href={`/teacher/assessments/${a.id}`} className="text-xs font-bold text-[#20407D] hover:text-[#C72323] hover:underline">
                              Open
                            </Link>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>

        {/* Target Metrics */}
        <div className="space-y-4">
          <h3 className="text-base font-bold text-gray-900">Standard Target Metrics</h3>
          <div className="bg-white/80 border border-gray-300 rounded-none p-6 space-y-6 shadow-sm backdrop-blur-sm">
            {[
              { label: "Participation Turnout", desc: "High student response rates across activated batches.", value: "96%", color: "stroke-emerald-600", offset: "15.0" },
              { label: "Educator Pass Metrics", desc: "Dynamic evaluation grading benchmark averages.", value: "88%", color: "stroke-[#20407D]", offset: "18.0" },
            ].map((gauge) => (
              <div key={gauge.label} className="flex items-center gap-4">
                <div className="relative h-14 w-14 flex items-center justify-center shrink-0">
                  <svg className="w-full h-full transform -rotate-90">
                    <circle cx="28" cy="28" r="24" className="stroke-gray-200 fill-transparent" strokeWidth="4" />
                    <circle cx="28" cy="28" r="24" className={`${gauge.color} fill-transparent`} strokeWidth="4" strokeDasharray="150.7" strokeDashoffset={gauge.offset} />
                  </svg>
                  <span className="absolute text-xs font-bold text-gray-800">{gauge.value}</span>
                </div>
                <div>
                  <p className="text-xs font-bold text-gray-800">{gauge.label}</p>
                  <p className="text-[10px] text-gray-600 leading-relaxed mt-0.5 font-medium">{gauge.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

