"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Globe, Lock, BookOpen, Clock, Users, Loader, AlertCircle } from "lucide-react";

export default function AdminAssessmentDetailPage() {
  const router = useRouter();
  const params = useParams();
  const id = params?.id as string;

  const [token, setToken] = useState<string | null>(null);
  const [assessment, setAssessment] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const t = localStorage.getItem("adminToken");
    if (!t) { router.push("/admin/login"); return; }
    setToken(t);
  }, []);

  useEffect(() => {
    if (!token || !id) return;
    // Reuse teacher assessment API — admin token will work with the existing route
    fetch(`/api/teacher/assessment/${id}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((r) => r.json())
      .then((data) => {
        if (data.assessment) {
          const a = data.assessment;
          setAssessment({ ...a, questions: Array.isArray(a.questions) ? a.questions : JSON.parse(a.questions || "[]") });
        } else {
          setError(data.message || "Assessment not found.");
        }
      })
      .catch(() => setError("Failed to load assessment."))
      .finally(() => setLoading(false));
  }, [token, id]);

  if (loading) return (
    <div className="p-8 h-96 flex items-center justify-center">
      <div className="flex flex-col items-center gap-3 text-slate-500">
        <Loader size={28} className="animate-spin text-indigo-400" />
        <p className="text-sm">Loading...</p>
      </div>
    </div>
  );

  if (error || !assessment) return (
    <div className="p-8 space-y-4">
      <Link href="/admin/assessments" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white">
        <ArrowLeft size={16} /> Back to Assessments
      </Link>
      <div className="bg-rose-500/10 border border-rose-500/20 rounded-2xl p-6 text-rose-400 flex items-center gap-3">
        <AlertCircle size={20} />{error || "Not found."}
      </div>
    </div>
  );

  const questions = assessment.questions || [];

  return (
    <div className="p-8 space-y-6 animate-in fade-in slide-in-from-bottom duration-300">
      {/* Header */}
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link href="/admin/assessments" className="p-2.5 bg-slate-900 border border-white/5 rounded-xl hover:bg-slate-800 text-slate-400 hover:text-white transition-colors">
            <ArrowLeft size={16} />
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-black">{assessment.title}</h2>
              <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                assessment.isPublic ? "bg-indigo-500/10 text-indigo-400 border border-indigo-500/20" : "bg-slate-800 text-slate-400 border border-white/5"
              }`}>
                {assessment.isPublic ? <Globe size={9} /> : <Lock size={9} />}
                {assessment.isPublic ? "Public" : "Private"}
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-0.5">
              Generated by <span className="text-indigo-400 font-bold">{assessment.createdByTeacherName}</span> ({assessment.createdByEmail}) · {new Date(assessment.createdAt).toLocaleDateString()}
            </p>
          </div>
        </div>
      </div>

      {/* Meta cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { icon: BookOpen, label: "Subject", value: assessment.subject, color: "text-indigo-400" },
          { icon: Clock, label: "Duration", value: `${assessment.duration} mins`, color: "text-indigo-400" },
          { icon: BookOpen, label: "Chapter", value: assessment.lesson, color: "text-indigo-400" },
          { icon: Users, label: "Questions", value: `${questions.length} items`, color: "text-indigo-400" },
        ].map(({ icon: Icon, label, value, color }) => (
          <div key={label} className="bg-slate-900/40 border border-white/5 rounded-2xl p-5 flex items-center gap-4">
            <Icon className={color} size={20} />
            <div>
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-500">{label}</label>
              <p className="text-sm font-bold text-slate-200 mt-0.5">{value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Questions (read-only) */}
      <div className="space-y-4">
        <h3 className="text-base font-bold">{questions.length} Questions (Read-Only Audit View)</h3>
        {questions.map((q: any, idx: number) => (
          <div key={idx} className="bg-slate-900/40 border border-white/5 rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <span className="h-6 w-6 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center justify-center font-bold text-[10px]">{idx + 1}</span>
              <span className="text-[9px] font-black uppercase tracking-widest text-slate-500">{q.type?.replace("_", " ")}</span>
            </div>

            <p className="text-sm font-bold text-slate-100 mb-4">{q.question}</p>

            {q.type === "multiple_choice" && q.options?.length > 0 && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mb-4">
                {q.options.map((opt: string, optIdx: number) => (
                  <div key={optIdx} className="flex items-center gap-2">
                    <span className="text-[10px] font-black text-indigo-400 shrink-0">{String.fromCharCode(65 + optIdx)}.</span>
                    <span className="w-full bg-slate-950/50 border border-white/5 rounded-xl px-3 py-2 text-xs text-slate-300">{opt}</span>
                  </div>
                ))}
              </div>
            )}

            <div className="p-3 bg-emerald-500/5 border border-emerald-500/10 rounded-xl space-y-1">
              <p className="text-[10px] font-bold text-emerald-400">
                ✔ Answer: <span className="text-white font-extrabold">{q.correctAnswer}</span>
              </p>
              {q.explanation && (
                <p className="text-[10px] text-slate-500 italic leading-relaxed">{q.explanation}</p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
