"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Globe, Lock, BookOpen, Clock, Users, Loader, AlertCircle } from "lucide-react";

export default function AdminAssessmentDetailPage() {
  const router = useRouter();
  const params = useParams();
  const id = params?.id as string;

  const [token, setToken] = useState<string | null>(null);
  const [assessment, setAssessment] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const t = localStorage.getItem("adminToken");
    if (!t) { router.push("/admin/login"); return; }
    setToken(t);
  }, []);

  useEffect(() => {
    if (!token || !id) return;
    fetch(`/api/teacher/assessment/${id}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((r) => r.json())
      .then((data) => {
        if (data.assessment) {
          const a = data.assessment;
          setAssessment({ ...a, questions: Array.isArray(a.questions) ? a.questions : JSON.parse(a.questions || "[]") });
        } else {
          setError(data.message || "Assessment not found.");
        }
      })
      .catch(() => setError("Failed to load assessment."))
      .finally(() => setLoading(false));
  }, [token, id]);

  if (loading) return (
    <div className="p-8 h-96 flex items-center justify-center text-gray-900">
      <div className="flex flex-col items-center gap-3 text-gray-500">
        <Loader size={28} className="animate-spin text-[#20407D]" />
        <p className="text-sm font-bold">Loading assessment details...</p>
      </div>
    </div>
  );

  if (error || !assessment) return (
    <div className="p-8 space-y-4 text-gray-900">
      <Link href="/admin/assessments" className="inline-flex items-center gap-2 text-sm text-[#20407D] hover:text-[#C72323] transition-colors font-bold">
        <ArrowLeft size={16} /> Back to Assessments
      </Link>
      <div className="bg-red-50 border border-red-200 rounded-none p-6 text-[#C72323] flex items-center gap-3 font-semibold shadow-sm">
        <AlertCircle size={20} />{error || "Not found."}
      </div>
    </div>
  );

  const questions = assessment.questions || [];

  return (
    <div className="p-8 space-y-6 animate-in fade-in slide-in-from-bottom duration-300 text-gray-900">
      {/* Header */}
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link 
            href="/admin/assessments" 
            className="p-2.5 bg-white border border-gray-300 rounded-none hover:bg-gray-100 text-gray-700 hover:text-gray-900 transition-colors shadow-sm cursor-pointer"
          >
            <ArrowLeft size={16} />
          </Link>
          <div>
            <div className="flex items-center gap-3">
              <h2 className="text-2xl font-black tracking-tight text-gray-900">{assessment.title}</h2>
              <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-none text-[10px] font-bold border ${
                assessment.isPublic 
                  ? "bg-[#20407D]/10 text-[#20407D] border-[#20407D]/20" 
                  : "bg-gray-100 text-gray-600 border-gray-300"
              }`}>
                {assessment.isPublic ? <Globe size={9} /> : <Lock size={9} />}
                {assessment.isPublic ? "Public" : "Private"}
              </span>
            </div>
            <p className="text-xs text-gray-600 mt-1 font-medium">
              Generated by <span className="text-[#20407D] font-bold">{assessment.createdByTeacherName}</span> ({assessment.createdByEmail}) · {new Date(assessment.createdAt).toLocaleDateString()}
            </p>
          </div>
        </div>
      </div>

      {/* Meta cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { icon: BookOpen, label: "Subject", value: assessment.subject, color: "text-[#20407D]" },
          { icon: Clock, label: "Duration", value: `${assessment.duration} mins`, color: "text-[#20407D]" },
          { icon: BookOpen, label: "Chapter", value: assessment.lesson, color: "text-[#20407D]" },
          { icon: Users, label: "Questions", value: `${questions.length} items`, color: "text-[#20407D]" },
        ].map(({ icon: Icon, label, value, color }) => (
          <div key={label} className="bg-white/80 border border-gray-300 rounded-none p-5 flex items-center gap-4 shadow-sm backdrop-blur-sm">
            <Icon className={color} size={20} />
            <div>
              <label className="text-[9px] uppercase tracking-wider font-bold text-gray-500 block">{label}</label>
              <p className="text-sm font-bold text-gray-800 mt-0.5">{value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Questions (read-only) */}
      <div className="space-y-4">
        <h3 className="text-base font-bold text-gray-900 border-b border-gray-200 pb-2">{questions.length} Questions (Read-Only Audit View)</h3>
        {questions.map((q: any, idx: number) => (
          <div key={idx} className="bg-white/80 border border-gray-300 rounded-none p-6 shadow-sm backdrop-blur-sm">
            <div className="flex items-center gap-2 mb-3">
              <span className="h-6 w-6 rounded-none bg-[#20407D]/10 border border-[#20407D]/20 text-[#20407D] flex items-center justify-center font-bold text-[10px]">{idx + 1}</span>
              <span className="text-[9px] font-black uppercase tracking-widest text-gray-500">{q.type?.replace("_", " ")}</span>
            </div>

            <p className="text-sm font-bold text-gray-950 mb-4">{q.question}</p>

            {q.type === "multiple_choice" && q.options?.length > 0 && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mb-4">
                {q.options.map((opt: string, optIdx: number) => (
                  <div key={optIdx} className="flex items-center gap-2">
                    <span className="text-xs font-black text-[#20407D] shrink-0 w-4">{String.fromCharCode(65 + optIdx)}.</span>
                    <span className="w-full bg-gray-50 border border-gray-200 rounded-none px-3 py-2 text-xs text-gray-800 font-medium">{opt}</span>
                  </div>
                ))}
              </div>
            )}

            <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-none space-y-1">
              <p className="text-[11px] font-bold text-emerald-800">
                ✔ Answer: <span className="text-emerald-950 font-extrabold">{q.correctAnswer}</span>
              </p>
              {q.explanation && (
                <p className="text-[10px] text-gray-600 italic leading-relaxed">{q.explanation}</p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

